version: '3.4'

services:
  mariadb:
    ports:
      - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
  homeapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__DefaultConnection=Server=mariadb;Database=homeapp;Uid=root;Pwd=root
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro